name: General

on: pull_request

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Fetch base ref
        run: git fetch origin ${{ github.base_ref }}
      - name: Install Go and Dependencies
        uses: ./.github/actions/install-go-and-deps
      - name: Build Mage
        uses: ./.github/actions/build-mage
      - name: Install Node and Dependencies
        uses: ./.github/actions/install-node-and-deps
      - name: Check headers
        run: tools/bin/mage headers:check headers:checkNewFiles
      - name: Fix common spelling mistakes
        run: tools/bin/mage dev:misspell
      - name: Format SQL files
        run: tools/bin/mage sql:fmt
      - name: Format proto files
        run: tools/bin/mage proto:fmt
      - name: Check for diff
        run: tools/bin/mage git:diff
